### ISSUE TITLE
Pakistan to Saudi currency is not working 

### ISSUE THREAD

**Issue by badarshahzad** [naeemkhan12/CurrencyConverter#1]
Well with my clumsy English it will be difficult to explain bug but here is short giff I made for you to get a click what wrong in it.
 [Pak into Saudi](http://gph.is/2f96cUH)

**Comment by naeemrashid** [comment]
Unfortunately not all currencies are supported by http://api.fixer.io :disappointed: . Pakistan's currency code is PKR which is not included in supported currencies list. Head to the Limitations section https://github.com/naeemkhan12/CurrencyConverter. :+1:
